### PR TITLE
refactoring and automatic scripts

### PR DESCRIPTION
**Pull request by gmat**
Some changes to use the setup.py automatic scripts feature

### CODE REVIEW

**Comment by gmat** [comment]
Don't really test but should work

**Comment by gmat** [comment]
...and the code in the __main__ won't be useful in most of the time

**Comment by sgsokol** [comment]
It should work where, on Windows? Only? And all my tests which refer to influx_s.py, influx_i.py, and other .py, should I rewrite them all too? I think that I won't do this. Too much intrusive as PR. Sorry.

**Comment by gmat** [comment]
You can refused this PR.
It should be refused not because is too intrusive but  because is not enough :) 
I should have check your tests and also patch the documentation to remove the .py in all command line examples.
Maybe the influx_s.py, influx_i.py and other scripts in .py names could be keeping for compatibility use only (work on linux but not on windows).
Same changes should also have been done for the other .py in the bin/ folder.
Maybe if you want, I can help you in this task on a new branch.

**Comment by sgsokol** [comment]
I'll try to find a less work demanding solution.

**Pull request closed without merging**
